version: "3"
services:
  redis-ms:
    image: redis:6.0.7
    container_name: redis-ms
    restart: always
    volumes:
      - .:/app/redis_data
    ports:
      - 6378:6379

  customer-ms:
    #container_name: customer-ms
    build: .
    env_file:
      - ./.env
    depends_on:
      - "redis-ms"  

    
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    container_name: nginx  
    depends_on:
      - customer-ms
      - "redis-ms"  
    ports:
      - 8001:8001

    